"""add user profile fields and friend code

Revision ID: 100dc7028bf1
Revises: fc49efb43f93
Create Date: 2026-05-19 22:26:44.201947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100dc7028bf1'
down_revision = 'fc49efb43f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('display_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('friend_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notification_prefs', sa.String(), server_default='all', nullable=True))
        batch_op.add_column(sa.Column('privacy_mode', sa.String(), server_default='friends', nullable=True))
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), server_default='0', nullable=True))
        batch_op.create_index(batch_op.f('ix_users_friend_code'), ['friend_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_friend_code'))
        batch_op.drop_column('dark_mode')
        batch_op.drop_column('privacy_mode')
        batch_op.drop_column('notification_prefs')
        batch_op.drop_column('friend_code')
        batch_op.drop_column('display_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
