"""add seasons_watched to watchlist_items

Revision ID: 17f4ad1e9fa7
Revises: 100dc7028bf1
Create Date: 2026-05-19 22:55:15.007027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f4ad1e9fa7'
down_revision = '100dc7028bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seasons_watched', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_column('seasons_watched')

    # ### end Alembic commands ###
