"""add streaming_service_taps

Revision ID: 180cc0d7fd81
Revises: 617d34b64050
Create Date: 2026-05-20 13:30:54.893404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180cc0d7fd81'
down_revision = '617d34b64050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming_service_taps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('tap_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_tapped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_name', name='uq_user_service')
    )
    with op.batch_alter_table('streaming_service_taps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streaming_service_taps_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_service_taps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streaming_service_taps_user_id'))

    op.drop_table('streaming_service_taps')
    # ### end Alembic commands ###
