"""add streaming_cache table

Revision ID: 1edf0aa277ef
Revises: 17f4ad1e9fa7
Create Date: 2026-05-19 23:09:23.871631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edf0aa277ef'
down_revision = '17f4ad1e9fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming_cache',
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('imdb_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streaming_cache')
    # ### end Alembic commands ###
