"""add pro_status to users

Revision ID: 4dc2656656b2
Revises: e65e712091e4
Create Date: 2026-05-21 23:53:05.860655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc2656656b2'
down_revision = 'e65e712091e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pro_status', sa.String(), server_default='free', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pro_status')

    # ### end Alembic commands ###
