"""add media_type to watchlist_items

Revision ID: 51dcfed41b98
Revises: dd1b1890fbc7
Create Date: 2026-05-19 20:35:01.777671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51dcfed41b98'
down_revision = 'dd1b1890fbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(), server_default='movie', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
