"""create missing friendships, recommendations, review_shares tables

Revision ID: 557e3dc5ddc9
Revises: 73245f3f1853
Create Date: 2026-06-03 22:12:06.939311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557e3dc5ddc9'
down_revision = '73245f3f1853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_id'), ['requester_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='movie', nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_to_user_id'), ['to_user_id'], unique=False)

    op.create_table('review_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('rec_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='unread', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rec_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_shares_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_shares_to_user_id'), ['to_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_shares_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_shares_from_user_id'))

    op.drop_table('review_shares')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_from_user_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_id'))

    op.drop_table('friendships')
    # ### end Alembic commands ###
