"""add friendship, recommendation, review_share tables and recommended_by_user_id

Revision ID: 617d34b64050
Revises: 1edf0aa277ef
Create Date: 2026-05-19 23:43:56.491369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617d34b64050'
down_revision = '1edf0aa277ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_watchlist_recommended_by_user_id', 'users', ['recommended_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_watchlist_recommended_by_user_id', type_='foreignkey')
        batch_op.drop_column('recommended_by_user_id')

    # ### end Alembic commands ###
