"""add genres preference to users

Revision ID: 73245f3f1853
Revises: 4dc2656656b2
Create Date: 2026-06-01 09:50:08.970356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73245f3f1853'
down_revision = '4dc2656656b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
