"""add movie night sessions and runtime_minutes

Revision ID: e65e712091e4
Revises: 180cc0d7fd81
Create Date: 2026-05-20 14:18:15.352419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65e712091e4'
down_revision = '180cc0d7fd81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_night_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('picked_imdb_id', sa.String(), nullable=False),
    sa.Column('picked_title', sa.String(), nullable=False),
    sa.Column('picked_year', sa.String(), nullable=True),
    sa.Column('picked_poster', sa.String(), nullable=True),
    sa.Column('picked_media_type', sa.String(), nullable=False),
    sa.Column('filter_max_runtime', sa.Integer(), nullable=True),
    sa.Column('filter_mood', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], name='fk_night_session_host'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie_night_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_night_sessions_host_user_id'), ['host_user_id'], unique=False)

    op.create_table('movie_night_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['movie_night_sessions.id'], name='fk_night_participant_session'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_night_participant_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_session_user')
    )
    with op.batch_alter_table('movie_night_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_night_participants_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_night_participants_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_column('runtime_minutes')

    with op.batch_alter_table('movie_night_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_night_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_movie_night_participants_session_id'))

    op.drop_table('movie_night_participants')
    with op.batch_alter_table('movie_night_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_night_sessions_host_user_id'))

    op.drop_table('movie_night_sessions')
    # ### end Alembic commands ###
