"""add omdb metadata columns to watchlist_items

Revision ID: fc49efb43f93
Revises: 51dcfed41b98
Create Date: 2026-05-19 21:30:14.357729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc49efb43f93'
down_revision = '51dcfed41b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('actors', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('imdb_rating', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rated', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('released', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_column('released')
        batch_op.drop_column('rated')
        batch_op.drop_column('imdb_rating')
        batch_op.drop_column('actors')
        batch_op.drop_column('director')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
